- name: Install required system packages.
  apt: pkg={{ item }}
  sudo: yes
  with_items:
  - python-pip
  - python-dev
  - python-dev
  - build-essential
  - libfreetype6
  - libfreetype6-dev
  - libatlas-base-dev 
  - gfortran
  - libc6
  - libfreetype6
  - libgcc1
  - libgdk-pixbuf2.0-0
  - libglib2.0-0
  - libgtk2.0-0
  - libpng12-0
  - libpng12-dev
  - libstdc++6
  - python-tk
  - tk
  - tk-dev
  - libboost-all-dev
  - gdb
- name: Install required Python packages.
  pip: name={{ item }} state=latest
  sudo: yes
  with_items:
  - pip
  - distribute
  - ipython
  - ipdb
  - matplotlib
  - numpy 
  - scipy
  - pytest
  - cython
  - pyublas
